### ISSUE TITLE
Cannot build the latest version.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#263]
./build.py 
Building version: v5.34.0-14-gf043e34
Cleaning dist...
Generating all build tasks...
Downloading Go modules...
Downloading WinTun from "https://www.wintun.net/builds/wintun-0.14.1.zip"...
Executing build tasks...
Starting: Go build client-linux-amd64
# github.com/quic-go/quic-go/internal/qtls
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:18:15: undefined: qtls.Alert
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:24:26: undefined: qtls.CipherSuiteTLS13
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:36:25: undefined: qtls.ConnectionStateWith0RTT
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:38:25: undefined: qtls.EncryptionLevel
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:40:19: undefined: qtls.Extension
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:44:21: undefined: qtls.RecordLayer
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:49:29: undefined: qtls.EncryptionHandshake
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:51:24: undefined: qtls.Encryption0RTT
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:53:31: undefined: qtls.EncryptionApplication
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: undefined: qtls.AEADAESGCMTLS13
../../../go/pkg/mod/github.com/quic-go/quic-go@v0.36.0/internal/qtls/go120.go:58:14: too many errors
Done: Go build client-linux-amd64
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 489, in <module>
    main()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 455, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 204, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 192, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call_addenv([self.gocmd, "build", "-trimpath", "-ldflags",
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 148, in check_call_addenv
    return check_call(args, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['go', 'build', '-trimpath', '-ldflags', "-w -s -X 'github.com/Doridian/wsvpn/shared.Version=v5.34.0-14-gf043e34'", '-o', 'dist/client-linux-amd64', './client']' returned non-zero exit status 1.

**Comment by Doridian** [comment]
Seems the `qtls` guys have pushed a new version too soon. Currently pushing a change to build in CI on 1.20 to make sure builds can't break on 1.20 by automatic version upgrades.

Issue will be fixed once the above is merged.
